// <auto-generated />
using System;
using Manager.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221103133028_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Manager.Data.Entity.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 20,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8855),
                            IsDeleted = false,
                            Name = "Huu Tai",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8868)
                        },
                        new
                        {
                            Id = 2L,
                            Age = 20,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8914),
                            IsDeleted = false,
                            Name = "Huy Hieu",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8915)
                        },
                        new
                        {
                            Id = 3L,
                            Age = 21,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8930),
                            IsDeleted = false,
                            Name = "Van Hoang",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8931)
                        },
                        new
                        {
                            Id = 4L,
                            Age = 20,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8943),
                            IsDeleted = false,
                            Name = "Anh Kiet",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 30, 28, 482, DateTimeKind.Local).AddTicks(8944)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
