// <auto-generated />
using System;
using Manager.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221103133837_init3")]
    partial class init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Manager.Data.Entity.ClassRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(842),
                            IsDeleted = false,
                            Name = "CNTT K18 A",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(857)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(901),
                            IsDeleted = false,
                            Name = "Quản trị kinh doanh",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(902)
                        });
                });

            modelBuilder.Entity("Manager.Data.Entity.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<long>("ClassRoomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 20,
                            ClassRoomId = 1L,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(922),
                            IsDeleted = false,
                            Name = "Huu Tai",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(923)
                        },
                        new
                        {
                            Id = 2L,
                            Age = 20,
                            ClassRoomId = 2L,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(949),
                            IsDeleted = false,
                            Name = "Huy Hieu",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(950)
                        },
                        new
                        {
                            Id = 3L,
                            Age = 21,
                            ClassRoomId = 1L,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(966),
                            IsDeleted = false,
                            Name = "Van Hoang",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(967)
                        },
                        new
                        {
                            Id = 4L,
                            Age = 20,
                            ClassRoomId = 2L,
                            CreatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(981),
                            IsDeleted = false,
                            Name = "Anh Kiet",
                            UpdatedAt = new DateTime(2022, 11, 3, 20, 38, 37, 223, DateTimeKind.Local).AddTicks(982)
                        });
                });

            modelBuilder.Entity("Manager.Data.Entity.Student", b =>
                {
                    b.HasOne("Manager.Data.Entity.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("Manager.Data.Entity.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
